version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: npm install
      - run: npm run test:ci
      - run:
          name: Upload coverage
          command: 'bash <(curl -s https://codecov.io/bash)'
      - store_artifacts:
          path: junit.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
         path: junit.xml